# Site
repository: AvinashChavanN/avinashchavann.github.io
favicon: favicon.ico.png
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Avinash Chavan
title: Javascript Enthusiast and Modern Web Application Developer
email: chvn.avi@gmail.com
phone: +1 (682) 347 6514
website: https://github.com/avinashchavann

# Social links
github_username:  avinashchavann
linkedin_username: avinash-chavan

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  -	A creative and passionate modern web development professional with around 10 years of experience using <mark>Javascript</mark> and multiple libraries such as <mark>Reactjs, Nextjs, Vuejs</mark> along with HTML5, and CSS to build all aspects of the user experience and user interface for client-facing landing pages. and <mark>Nodejs</mark>. 

  -	Full stack development of web applications in e-commerce and creative cloud engineer.
    
# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  -	<mark>Front-End:</mark> NextJS, React, Redux, VueJS, HTML5, CSS3, JavaScript, TypeScript, SASS, SCSS, Tailwind
  -	<mark>Back-End:</mark> Node, Express
  -	<mark>Build Deploy and Version Control Tools:</mark> Git, Azure DevOps Jenkins, Sourcetree, BitBucket
  -	<mark>SQL Database:</mark> Oracle, MySQL, Postgres SQL 
  -	<mark>NoSQL:</mark> mongoDB, Neo4j
  -	<mark>Cloud Platforms:</mark> Azure, AWS
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

#Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

theme: jekyll-theme-architect
